// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NObdDyVk9xjAq-_Ohsn9iskWKPHcwmY',
    appId: '1:825262768905:web:43e7b25d8f6653c6b209d8',
    messagingSenderId: '825262768905',
    projectId: 'fir-2fe71',
    authDomain: 'fir-2fe71.firebaseapp.com',
    storageBucket: 'fir-2fe71.appspot.com',
    measurementId: 'G-T61NFC10PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9v8yBqs768O5uwxRx_R9zQrpR5BWecI',
    appId: '1:825262768905:android:e37d4b8e1809446fb209d8',
    messagingSenderId: '825262768905',
    projectId: 'fir-2fe71',
    storageBucket: 'fir-2fe71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGDBgmK6ffPE1zh787PUeCnU1vzPuCHuI',
    appId: '1:825262768905:ios:fa5b4b8a793f325cb209d8',
    messagingSenderId: '825262768905',
    projectId: 'fir-2fe71',
    storageBucket: 'fir-2fe71.appspot.com',
    iosClientId: '825262768905-ui1p5bsvvuhtbgdfg7j2udtt53gpg0f3.apps.googleusercontent.com',
    iosBundleId: 'com.firebase.presents.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGDBgmK6ffPE1zh787PUeCnU1vzPuCHuI',
    appId: '1:825262768905:ios:fa5b4b8a793f325cb209d8',
    messagingSenderId: '825262768905',
    projectId: 'fir-2fe71',
    storageBucket: 'fir-2fe71.appspot.com',
    iosClientId: '825262768905-ui1p5bsvvuhtbgdfg7j2udtt53gpg0f3.apps.googleusercontent.com',
    iosBundleId: 'com.firebase.presents.netflix',
  );
}
